export const RedirectionRoutes = {
  index: "/",
  signIn: "/signin",
  signUp: "/signup",
  dashboard: "/dashboard",
  //sales
  sales: "/sales",
  customer: "/sales/customers",
  customerNew: "/sales/customers/new",
  customerDetail: "/sales/customers/view/:id",
  customerEdit: "/sales/customers/:id",
  quotes: "/sales/quotes",
  quotesNew: "/sales/quotes/new",
  quotesDetail: "/sales/quotes/detail/:id",
  quotesEdit: "/sales/quotes/:id",
  invoices: "/sales/invoices",
  invoicesNew: "/sales/invoices/new",
  invoicesEdit: "/sales/invoices/:id",
  //purchase
  purchase: "/purchases",
  banking: "/banking",
  inventory: "inventory",
  reports: "/reports",
  settings: "/settings",
  subscription: "/subscription",
  organization: "/organization",
  uiComponents: "/ui-components",
};
